language: cpp

matrix:
  include:
    - os: linux
      dist: xenial
      sudo: required
      compiler:
        - gcc
        - clang
      env:
        - QT_BASE=57
    - os: linux
      dist: xenial
      sudo: required
      compiler: gcc
      env:
        - QT_BASE=512
    - os: linux
      dist: xenial
      sudo: required
      compiler: clang
      env:
        - QT_BASE=512
    - os: linux
      dist: xenial
      sudo: required
      compiler:
        - gcc
        - clang
      env:
        - QT_BASE=513
    - os: linux
      dist: xenial
      sudo: required
      compiler:
        - gcc
        - clang
      env:
        - QT_BASE=514
    - os: linux
      dist: xenial
      sudo: required
      compiler:
        - gcc
      env:
        - QT_BASE=515
    - os: linux
      dist: xenial
      sudo: required
      compiler:
        - clang
      env:
        - QT_BASE=515
    #- os: osx
      #compiler: clang
      #env:
        #- QT_BASE=512

git:
  submodules: false

before_install:
   - if [[ "$QT_BASE" = "57" && "$TRAVIS_OS_NAME" = "linux" ]]; then sudo add-apt-repository ppa:beineri/opt-qt571-xenial -y; fi
   - if [[ "$QT_BASE" = "512" && "$TRAVIS_OS_NAME" = "linux" ]]; then sudo add-apt-repository ppa:beineri/opt-qt-5.12.9-xenial -y; fi
   - if [[ "$QT_BASE" = "513" && "$TRAVIS_OS_NAME" = "linux" ]]; then sudo add-apt-repository ppa:beineri/opt-qt-5.13.2-xenial -y; fi
   - if [[ "$QT_BASE" = "514" && "$TRAVIS_OS_NAME" = "linux" ]]; then sudo add-apt-repository ppa:beineri/opt-qt-5.14.2-xenial -y; fi
   - if [[ "$QT_BASE" = "515" && "$TRAVIS_OS_NAME" = "linux" ]]; then sudo add-apt-repository ppa:beineri/opt-qt-5.15.2-xenial -y; fi
   - if [ "$TRAVIS_OS_NAME" = "linux" ]; then
       sudo apt update -qq;
     else
       brew update;
     fi

install:
  - |
    sudo apt -y install gpm apt-file git wget unzip gcc make autoconf automake libtool \
    g++ autoconf-archive pkg-config libglib2.0-dev libglibmm-2.4-dev libzip-dev \
    libusb-1.0-0-dev libftdi1-dev libhidapi-dev libbluetooth-dev libvisa-dev libieee1284-3-dev \
    check doxygen python-numpy python-dev python-gi-dev python-setuptools swig sdcc \
    python3 python3-dev python3-numpy python3-setuptools python3-gi \
    libboost-all-dev mesa-common-dev libgl1-mesa-dev
  - if [[ "$QT_BASE" = "57" && "$TRAVIS_OS_NAME" = "linux" ]]; then sudo apt install -qq qt57base qt57svg; source /opt/qt57/bin/qt57-env.sh; fi
  - if [[ "$QT_BASE" = "512" && "$TRAVIS_OS_NAME" = "linux" ]]; then sudo apt install -qq qt512base qt512svg; source /opt/qt512/bin/qt512-env.sh; fi
  - if [[ "$QT_BASE" = "513" && "$TRAVIS_OS_NAME" = "linux" ]]; then sudo apt install -qq qt513base qt513svg; source /opt/qt513/bin/qt513-env.sh; fi
  - if [[ "$QT_BASE" = "514" && "$TRAVIS_OS_NAME" = "linux" ]]; then sudo apt install -qq qt514base qt514svg; source /opt/qt514/bin/qt514-env.sh; fi
  - if [[ "$QT_BASE" = "515" && "$TRAVIS_OS_NAME" = "linux" ]]; then sudo apt install -qq qt515base qt515svg; source /opt/qt515/bin/qt515-env.sh; fi
  #- if [ "$QT_BASE" = "57" ]; then
      #if [ "$TRAVIS_OS_NAME" = "linux" ]; then
        #sudo apt install -qq qt57base; source /opt/qt57/bin/qt57-env.sh;
      #else
        #brew install qt5;
        #brew link --force qt5;
      #fi
    #fi
  # Without pyenv, python37 is not found
  - pyenv local 3.7.1

script:
  # Build qwt
  - wget "https://sourceforge.net/projects/qwt/files/qwt/6.1.5/qwt-6.1.5.tar.bz2/download" --trust-server-names
  - tar xf qwt-*.tar.bz2
  - cd qwt-*/
  - qmake qwt.pro
  - make -j$(nproc)
  - sudo make install
  - cd ..
  # Build smuview
  - git clone https://github.com/knarfS/sigrok-util.git
  - cd sigrok-util
  - git checkout smuview
  - cd cross-compile/linux
  - ./sigrok-cross-linux-smuview

branches:
  except:
    - # Do not build tags that we create when we upload to GitHub Releases
    - /^(?i:continuous)/
    - flow
